"""
This file is meant to store a curated set of configurations for use in 
numerical experiments for thesis results.
"""
import autograd.numpy as np
from solvers.projected_common_directions import ProjectedCommonDirectionsConfig

# Dictionary to hold configuration parameters for all solver variants
solver_config_tree = {
    "sd": { # 
        'orth_Pk': { # orthogonalise Pk ?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "normalise_P_k_cols": False,
                "alpha_max": 100,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": False,
                "normalise_P_k_cols": True,
                "alpha_max": 100,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "normalise_P_k_cols": False,
                "alpha_max": 100,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": False,
                "normalise_P_k_cols": True,
                "alpha_max": 100,
            },
        },
        'haar_gauss': { # use Haar-orthonormal or Gauss matrices for sketching?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'scaled_gaussian',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'sd',
                "ensemble": 'scaled_gaussian',
                "orth_P_k": True,
                "alpha_max": 100,
            },
        },
        'sketch_size': { # What sketch size to use?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.05,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.4,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver5': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6, # NOTE: the reason we avoid random_proj_dim_frac = 0.8 (in a geometric series with the previous) is because this case expends more derivative information per iteration than if we just use the true (i.e. not even projected) gradient!
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'full-space-SD': {
                "subspace_frac_grads": 0,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
        },
        'sketch_size_further': { # What sketch size to use? NOTE: now using more problem-directions
            'solver1': {
                "subspace_frac_grads": 0.2,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.05,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver2': {
                "subspace_frac_grads": 0.2,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver3': {
                "subspace_frac_grads": 0.2,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver4': {
                "subspace_frac_grads": 0.2,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.4,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver5': {
                "subspace_frac_grads": 0.2,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6, # NOTE: the reason we avoid random_proj_dim_frac = 0.8 (in a geometric series with the previous) is because this case expends more derivative information per iteration than if we just use the true (i.e. not even projected) gradient!
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
            'solver6': {
                "subspace_frac_grads": 0,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },
        },
        'use_momentum': {
            'solver1': {
                "subspace_frac_grads":   0.18,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver2': {
                "subspace_frac_grads":   0.09,
                "subspace_frac_updates": 0.09,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver3': {
                "subspace_frac_grads":   0.09,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.09,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver4': {
                "subspace_frac_grads":   0.06,
                "subspace_frac_updates": 0.06,
                "subspace_frac_random":  0.06,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver5': {
                "subspace_frac_grads":   0.3,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver6': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0.15,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver7': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.15,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'solver8': {
                "subspace_frac_grads":   0.10,
                "subspace_frac_updates": 0.10,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
        },
        'granular': {
            'full-space-SD': {
                "subspace_frac_grads": 0,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },

            '1d.0.0': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.1d.0': {
                "subspace_no_grads":   1,
                "subspace_no_updates": 1,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.1': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.01,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.2': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.5': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.7': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.07,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.1d.5': {
                "subspace_no_grads":   1,
                "subspace_no_updates": 1,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.10': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.1d.10': {
                "subspace_no_grads":   1,
                "subspace_no_updates": 1,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.20': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.2,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.1d.20': {
                "subspace_no_grads":   1,
                "subspace_no_updates": 1,
                "subspace_frac_random":  0.2,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.40': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.4,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.1d.40': {
                "subspace_no_grads":   1,
                "subspace_no_updates": 1,
                "subspace_frac_random":  0.4,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },


            '2.0.0': {
                "subspace_frac_grads":   0.02,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '2.0.10': {
                "subspace_frac_grads":   0.02,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '2.2.0': {
                "subspace_frac_grads":   0.02,
                "subspace_frac_updates": 0.02,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '2.2.10': {
                "subspace_frac_grads":   0.02,
                "subspace_frac_updates": 0.02,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '3.0.0': {
                "subspace_frac_grads":   0.03,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '3.0.10': {
                "subspace_frac_grads":   0.03,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '3.3.0': {
                "subspace_frac_grads":   0.03,
                "subspace_frac_updates": 0.03,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '3.3.10': {
                "subspace_frac_grads":   0.03,
                "subspace_frac_updates": 0.03,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '4.0.0': {
                "subspace_frac_grads":   0.04,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '4.0.10': {
                "subspace_frac_grads":   0.04,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '4.4.0': {
                "subspace_frac_grads":   0.04,
                "subspace_frac_updates": 0.04,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '4.4.10': {
                "subspace_frac_grads":   0.04,
                "subspace_frac_updates": 0.04,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.0.0': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.0.10': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.0': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.2': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.5': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.10': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.20': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.20,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.40': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.40,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '7.0.0': {
                "subspace_frac_grads":   0.07,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '7.0.10': {
                "subspace_frac_grads":   0.07,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '7.7.0': {
                "subspace_frac_grads":   0.07,
                "subspace_frac_updates": 0.07,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '7.7.10': {
                "subspace_frac_grads":   0.07,
                "subspace_frac_updates": 0.07,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },


            '10.0.0': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '10.0.10': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },

            '10.10.0': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '10.10.5': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '10.10.10': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '10.10.20': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0.2,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },

            '15.0.0': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '15.0.10': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '15.15.0': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0.15,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '15.15.10': {
                "subspace_frac_grads":   0.15,
                "subspace_frac_updates": 0.15,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },

            '20.20.0': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '20.20.5': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '20.20.10': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '20.20.20': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.2,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
        },
    'benchmarks': {
            'full-space-SD': {
                "subspace_frac_grads": 0,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 100,
            },


            '1d.0.2-5%-SKETCH': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 0.05,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '1d.0.2-10%-SKETCH': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 0.10,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },

            '1d.0.2': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.10': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '5.5.20': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.20,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '10.10.10': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '20.20.5': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '20.20.10': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },


            'lee-1d.0.2': {
                "subspace_no_grads":   1,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.02,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'lee-5.5.10': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'lee-5.5.20': {
                "subspace_frac_grads":   0.05,
                "subspace_frac_updates": 0.05,
                "subspace_frac_random":  0.20,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'lee-10.10.10': {
                "subspace_frac_grads":   0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'lee-20.20.5': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            'lee-20.20.10': {
                "subspace_frac_grads":   0.2,
                "subspace_frac_updates": 0.2,
                "subspace_frac_random":  0.1,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },


            '0.0.5': {
                "subspace_frac_grads":   0,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.05,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '0.0.10': {
                "subspace_frac_grads":   0,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.10,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '0.0.20': {
                "subspace_frac_grads":   0,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.20,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '0.0.30': {
                "subspace_frac_grads":   0,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.30,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
            '0.0.50': {
                "subspace_frac_grads":   0,
                "subspace_frac_updates": 0,
                "subspace_frac_random":  0.50,
                "random_proj_dim_frac": 1,
                "direction_str": 'sd',
                "ensemble": 'haar',
                "alpha_max": 100,
            },
        }
    },
    "newton": {
        'orth_Pk': { # orthogonalise Pk ?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "normalise_P_k_cols": False,
                "alpha_max": 1,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": False,
                "normalise_P_k_cols": True,
                "alpha_max": 1,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "normalise_P_k_cols": False,
                "alpha_max": 1,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": False,
                "normalise_P_k_cols": True,
                "alpha_max": 1,
            },
        },
        'haar_gauss': { # use Haar-orthonormal or Gauss matrices for sketching?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'newton',
                "ensemble": 'scaled_gaussian',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6,
                "direction_str": 'newton',
                "ensemble": 'scaled_gaussian',
                "orth_P_k": True,
                "alpha_max": 1,
            },
        },
        'sketch_size': { # What sketch size to use?
            'solver1': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.05,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver2': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.1,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver3': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.2,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver4': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.4,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver5': {
                "subspace_frac_grads": 0.1,
                "subspace_frac_updates": 0.1,
                "subspace_frac_random": 0.1,
                "random_proj_dim_frac": 0.6, # NOTE: the reason we avoid random_proj_dim_frac = 0.8 (in a geometric series with the previous) is because this case expends more derivative information per iteration than if we just use the true (i.e. not even projected) gradient!
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
            'solver6': {
                "subspace_frac_grads": 0,
                "subspace_frac_updates": 0,
                "subspace_frac_random": 1,
                "random_proj_dim_frac": 1,
                "direction_str": 'newton',
                "ensemble": 'haar',
                "orth_P_k": True,
                "alpha_max": 1,
            },
        },
    },
    
################################################################################
    
    "sample_solvers": {
        "solver0": {
            "subspace_no_grads": 1,
            "subspace_no_updates": 1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.2,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": True,
            "normalise_P_k_cols": False,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 1,
            "N_try": 100,
        },
        "solver1": {
            "subspace_frac_grads": 0.1,
            "subspace_frac_updates": 0.1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.2,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": False,
            "normalise_P_k_cols": True,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 1,
            "N_try": 100,
        },
        "solver2": {
            "subspace_frac_grads": 0.1,
            "subspace_frac_updates": 0.1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.2,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": True,
            "normalise_P_k_cols": False,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 1,
            "N_try": 100,
        },
        "solver3": {
            "subspace_frac_grads": 0.1,
            "subspace_frac_updates": 0.1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.4,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": False,
            "normalise_P_k_cols": True,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 1,
            "N_try": 100,
        },
        "solver4": {
            "subspace_frac_grads": 0.1,
            "subspace_frac_updates": 0.1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.2,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": True,
            "normalise_P_k_cols": False,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 1,
            "N_try": 100,
        },
        "solver5": {
            "subspace_frac_grads": 0.1,
            "subspace_frac_updates": 0.1,
            "subspace_frac_random": 0.1,
            "random_proj_dim_frac": 0.2,
            "direction_str": 'sd',
            "reg_lambda": 0.01,
            "ensemble": 'haar',
            "orth_P_k": True,
            "normalise_P_k_cols": False,
            "alpha_max": 100,
            "tau": 0.5,
            "c_const": 100,
            "N_try": 100,
        },
    },
    "solve_best": {
        "subspace_frac_grads": 0,
        "subspace_frac_updates": 0,
        "subspace_frac_random": 1,
        "random_proj_dim_frac": 0,
        "direction_str": 'newton',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": True,
        "normalise_P_k_cols": False,
        "alpha_max": 1,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
    "full_sd": {
        "subspace_frac_grads": 0,
        "subspace_frac_updates": 0,
        "subspace_frac_random": 1,
        "random_proj_dim_frac": 0,
        "direction_str": 'sd',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": True,
        "normalise_P_k_cols": False,
        "alpha_max": 1,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
    "full_newton": {
        "subspace_frac_grads": 0,
        "subspace_frac_updates": 0,
        "subspace_frac_random": 1,
        "random_proj_dim_frac": 0,
        "direction_str": 'newton',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": True,
        "normalise_P_k_cols": False,
        "alpha_max": 1,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
    "lee2022_grads": {
        "subspace_frac_grads": 0.2,
        "subspace_frac_updates": 0,
        "subspace_frac_random": 0,
        "random_proj_dim_frac": 1,
        "direction_str": 'newton',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": True,
        "normalise_P_k_cols": False,
        "alpha_max": 1,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
    "lee2022_grads_updates": {
        "subspace_frac_grads": 0.1,
        "subspace_frac_updates": 0.1,
        "subspace_frac_random": 0,
        "random_proj_dim_frac": 1,
        "direction_str": 'newton',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": True,
        "normalise_P_k_cols": False,
        "alpha_max": 1,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
    "random_subspace": {
        "subspace_frac_grads": 0,
        "subspace_frac_updates": 0,
        "subspace_frac_random": 0.2,
        "random_proj_dim_frac": 0,
        "direction_str": 'sd',
        "reg_lambda": 0.01,
        "ensemble": 'haar',
        "orth_P_k": False,
        "normalise_P_k_cols": False,
        "alpha_max": 100,
        "tau": 0.5,
        "c_const": np.inf,
        "N_try": np.inf,
    },
}

# Function to create a configuration object for a given variant name
def create_config(obj, variant_name):
    variant = solver_config_tree[variant_name]
    return ProjectedCommonDirectionsConfig(obj=obj, **variant)